/**
 * Constitution of Kenya (2010) — chapter metadata index.
 *
 * This module ships in the initial JS bundle so the sidebar, search,
 * and 'jump to article' UI work without a network round-trip. Full
 * chapter bodies live in /public/data/constitution/chapter-<n>.json
 * and are fetched on demand via loadChapter().
 *
 * Regenerated by scripts/build-constitution.mjs — edit hand-authored
 * fields (summary / highlight) in EDITORIAL inside that script so they
 * survive a re-run.
 */

import type { ChapterMeta, ConstitutionChapter } from './types';

export const CONSTITUTION_META: ChapterMeta[] = [
  {
    number: 1,
    title: 'Sovereignty of the People and Supremacy of This Constitution',
    summary:
      'Power belongs to the people of Kenya and flows through the Constitution.',
    articleRange: [1, 3],
    articleTitles: [
      { number: 1, title: 'Sovereignty of the people' },
      { number: 2, title: 'Supremacy of this Constitution' },
      { number: 3, title: 'Defence of this Constitution' },
    ],
    dataPath: '/data/constitution/chapter-1.json',
    highlight:
      'All sovereign power belongs to the people — directly or through elected representatives.',
  },
  {
    number: 2,
    title: 'The Republic',
    summary:
      'Kenya as a sovereign, multi-party democratic state and its national values.',
    articleRange: [4, 11],
    articleTitles: [
      { number: 4, title: 'Declaration of the Republic' },
      { number: 5, title: 'Territory of Kenya' },
      { number: 6, title: 'Devolution and access to services' },
      { number: 7, title: 'National, official and other languages' },
      { number: 8, title: 'State and religion' },
      { number: 9, title: 'National symbols and national days' },
      { number: 10, title: 'National values and principles of governance' },
      { number: 11, title: 'Culture' },
    ],
    dataPath: '/data/constitution/chapter-2.json',
    highlight:
      'Article 10 binds every state officer to the rule of law, accountability and integrity.',
  },
  {
    number: 3,
    title: 'Citizenship',
    summary:
      'Who is a Kenyan citizen, how citizenship is acquired, and what it entitles you to.',
    articleRange: [12, 18],
    articleTitles: [
      { number: 12, title: 'Entitlements of citizens' },
      { number: 13, title: 'Retention and acquisition of citizenship' },
      { number: 14, title: 'Citizenship by birth' },
      { number: 15, title: 'Citizenship by registration' },
      { number: 16, title: 'Dual citizenship' },
      { number: 17, title: 'Revocation of citizenship' },
      { number: 18, title: 'Legislation on citizenship' },
    ],
    dataPath: '/data/constitution/chapter-3.json',
  },
  {
    number: 4,
    title: 'The Bill of Rights',
    summary:
      'The Bill of Rights — every fundamental freedom the state must protect, from life and dignity to housing, healthcare, and fair labour.',
    articleRange: [19, 59],
    articleTitles: [
      { number: 19, title: 'Rights and fundamental freedoms' },
      { number: 20, title: 'Application of Bill of Rights' },
      { number: 21, title: 'Implementation of rights and fundamental freedoms' },
      { number: 22, title: 'Enforcement of Bill of Rights' },
      { number: 23, title: 'Authority of courts to uphold and enforce the Bill of Rights' },
      { number: 24, title: 'Limitation of rights and fundamental freedoms' },
      { number: 25, title: 'Fundamental Rights and freedoms that may not be limited' },
      { number: 26, title: 'Right to life' },
      { number: 27, title: 'Equality and freedom from discrimination' },
      { number: 28, title: 'Human dignity' },
      { number: 29, title: 'Freedom and security of the person' },
      { number: 30, title: 'Slavery, servitude and forced labour' },
      { number: 31, title: 'Privacy' },
      { number: 32, title: 'Freedom of conscience, religion, belief and opinion' },
      { number: 33, title: 'Freedom of expression' },
      { number: 34, title: 'Freedom of the media' },
      { number: 35, title: 'Access to information' },
      { number: 36, title: 'Freedom of association' },
      { number: 37, title: 'Assembly, demonstration, picketing and petition' },
      { number: 38, title: 'Political rights' },
      { number: 39, title: 'Freedom of movement and residence' },
      { number: 40, title: 'Protection of right to property' },
      { number: 41, title: 'Labour relations' },
      { number: 42, title: 'Environment' },
      { number: 43, title: 'Economic and social rights' },
      { number: 44, title: 'Language and culture' },
      { number: 45, title: 'Family' },
      { number: 46, title: 'Consumer rights' },
      { number: 47, title: 'Fair administrative action' },
      { number: 48, title: 'Access to justice' },
      { number: 49, title: 'Rights of arrested persons' },
      { number: 50, title: 'Fair hearing' },
      { number: 51, title: 'Rights of persons detained, held in custody or imprisoned' },
      { number: 52, title: 'Interpretation of Part' },
      { number: 53, title: 'Children' },
      { number: 54, title: 'Persons with disabilities' },
      { number: 55, title: 'Youth' },
      { number: 56, title: 'Minorities and marginalised groups' },
      { number: 57, title: 'Older members of society' },
      { number: 58, title: 'State of emergency' },
      { number: 59, title: 'Kenya National Human Rights and Equality Commission' },
    ],
    dataPath: '/data/constitution/chapter-4.json',
    highlight:
      'Article 43 guarantees economic and social rights — housing, food, water, healthcare, social security — as enforceable promises.',
  },
  {
    number: 5,
    title: 'Land and Environment',
    summary:
      'Who owns land, how it is used, and the principles that govern Kenya\'s environment and natural resources.',
    articleRange: [60, 72],
    articleTitles: [
      { number: 60, title: 'Principles of land policy' },
      { number: 61, title: 'Classification of land' },
      { number: 62, title: 'Public land' },
      { number: 63, title: 'Community land' },
      { number: 64, title: 'Private land' },
      { number: 65, title: 'Landholding by non-citizens' },
      { number: 66, title: 'Regulation of land use and property' },
      { number: 67, title: 'National Land Commission' },
      { number: 68, title: 'Legislation on land' },
      { number: 69, title: 'Obligations in respect of the environment' },
      { number: 70, title: 'Enforcement of environmental rights' },
      { number: 71, title: 'Agreements relating to natural resource' },
      { number: 72, title: 'Legislation relating to the environment' },
    ],
    dataPath: '/data/constitution/chapter-5.json',
    highlight:
      'Article 62 classifies every inch of the country as public, community or private land — closing a colonial-era ambiguity.',
  },
  {
    number: 6,
    title: 'Leadership and Integrity',
    summary:
      'The ethical and legal standards every public officer must meet.',
    articleRange: [73, 80],
    articleTitles: [
      { number: 73, title: 'Responsibilities of leadership' },
      { number: 74, title: 'Oath of office of State officers' },
      { number: 75, title: 'Conduct of State officers' },
      { number: 76, title: 'Financial probity of State officers' },
      { number: 77, title: 'Restriction on activities of State officers' },
      { number: 78, title: 'Citizenship and leadership' },
      { number: 79, title: 'Legislation to establish the ethics and anti-corruption commission' },
      { number: 80, title: 'Legislation on leadership' },
    ],
    dataPath: '/data/constitution/chapter-6.json',
    highlight:
      'Chapter 6 is the promise Kenyans demand from every elected and appointed leader.',
  },
  {
    number: 7,
    title: 'Representation of the People',
    summary:
      'Elections, voter registration, and the constitutional foundations of political parties and the IEBC.',
    articleRange: [81, 92],
    articleTitles: [
      { number: 81, title: 'General principles for the electoral system' },
      { number: 82, title: 'Legislation on elections' },
      { number: 83, title: 'Registration as a voter' },
      { number: 84, title: 'Candidates for election and political parties to comply with code of conduct' },
      { number: 85, title: 'Eligibility to stand as an independent candidate' },
      { number: 86, title: 'Voting' },
      { number: 87, title: 'Electoral disputes' },
      { number: 88, title: 'Independent Electoral and Boundaries Commission' },
      { number: 89, title: 'Delimitation of electoral units' },
      { number: 90, title: 'Allocation of party list seats' },
      { number: 91, title: 'Basic requirements for political parties' },
      { number: 92, title: 'Legislation on political parties' },
    ],
    dataPath: '/data/constitution/chapter-7.json',
    highlight:
      'Article 81 sets the principles — universal suffrage, free and fair elections, gender balance — every vote must meet.',
  },
  {
    number: 8,
    title: 'The Legislature',
    summary:
      'Parliament — the National Assembly and the Senate, how they are composed, elected, and how laws are passed.',
    articleRange: [93, 128],
    articleTitles: [
      { number: 93, title: 'Establishment of Parliament' },
      { number: 94, title: 'Role of Parliament' },
      { number: 95, title: 'Role of the National Assembly' },
      { number: 96, title: 'Role of the Senate' },
      { number: 97, title: 'Membership of the National Assembly' },
      { number: 98, title: 'Membership of the Senate' },
      { number: 99, title: 'Qualifications and disqualifications for election as member of Parliament' },
      { number: 100, title: 'Promotion of representation of marginalised groups' },
      { number: 101, title: 'Election of members of Parliament' },
      { number: 102, title: 'Term of Parliament' },
      { number: 103, title: 'Vacation of office of member of Parliament' },
      { number: 104, title: 'Right of recall' },
      { number: 105, title: 'Determination of questions of membership' },
      { number: 106, title: 'Speakers and Deputy Speakers of Parliament' },
      { number: 107, title: 'Presiding in Parliament' },
      { number: 108, title: 'Party leaders' },
      { number: 109, title: 'Exercise of legislative powers' },
      { number: 110, title: 'Bills concerning county government' },
      { number: 111, title: 'Special Bills concerning county governments' },
      { number: 112, title: 'Ordinary Bills concerning county governments' },
      { number: 113, title: 'Mediation committees' },
      { number: 114, title: 'Money Bills' },
      { number: 115, title: 'Presidential assent and referral' },
      { number: 116, title: 'Coming into force of laws' },
      { number: 117, title: 'Powers, privileges and immunities' },
      { number: 118, title: 'Public access and participation' },
      { number: 119, title: 'Right to petition Parliament' },
      { number: 120, title: 'Official languages of Parliament' },
      { number: 121, title: 'Quorum' },
      { number: 122, title: 'Voting in Parliament' },
      { number: 123, title: 'Decisions of Senate' },
      { number: 124, title: 'Committees and Standing Orders' },
      { number: 125, title: 'Power to call for evidence' },
      { number: 126, title: 'Location of sittings of Parliament' },
      { number: 127, title: 'Parliamentary Service Commission' },
      { number: 128, title: 'Clerks and staff of Parliament' },
    ],
    dataPath: '/data/constitution/chapter-8.json',
    highlight:
      'Article 94 is emphatic — law in Kenya is made only by Parliament; no one else may usurp that role.',
  },
  {
    number: 9,
    title: 'The Executive',
    summary:
      'The national executive — the President, Deputy President, Cabinet, and Attorney-General — and the limits on their power.',
    articleRange: [129, 158],
    articleTitles: [
      { number: 129, title: 'Principles of executive authority' },
      { number: 130, title: 'The National Executive' },
      { number: 131, title: 'Authority of the President' },
      { number: 132, title: 'Functions of the President' },
      { number: 133, title: 'Power of mercy' },
      { number: 134, title: 'Exercise of presidential powers during temporary incumbency' },
      { number: 135, title: 'Decisions of the President' },
      { number: 136, title: 'Election of the President' },
      { number: 137, title: 'Qualifications and disqualifications for election as President' },
      { number: 138, title: 'Procedure at presidential election' },
      { number: 139, title: 'Death before assuming office' },
      { number: 140, title: 'Questions as to validity of presidential election' },
      { number: 141, title: 'Assumption of office of President' },
      { number: 142, title: 'Term of office of President' },
      { number: 143, title: 'Protection from legal proceedings' },
      { number: 144, title: 'Removal of President on grounds of incapacity' },
      { number: 145, title: 'Removal of President by impeachment' },
      { number: 146, title: 'Vacancy in the office of President' },
      { number: 147, title: 'Functions of the Deputy President' },
      { number: 148, title: 'Election and swearing-in of Deputy President' },
      { number: 149, title: 'Vacancy in the office of Deputy President' },
      { number: 150, title: 'Removal of Deputy President' },
      { number: 151, title: 'Remuneration and benefits of President and Deputy President' },
      { number: 152, title: 'Cabinet' },
      { number: 153, title: 'Decisions, responsibility and accountability of the Cabinet' },
      { number: 154, title: 'Secretary to the Cabinet' },
      { number: 155, title: 'Principal Secretaries' },
      { number: 156, title: 'Attorney-General' },
      { number: 157, title: 'Director of Public Prosecutions' },
      { number: 158, title: 'Removal and resignation of Director of Public Prosecutions' },
    ],
    dataPath: '/data/constitution/chapter-9.json',
    highlight:
      'Article 142 caps every President at two five-year terms — Kenya\'s core guard-rail against executive entrenchment.',
  },
  {
    number: 10,
    title: 'Judiciary',
    summary:
      'How Kenya\'s courts are structured, who appoints judges, and how judicial independence is protected.',
    articleRange: [159, 173],
    articleTitles: [
      { number: 159, title: 'Judicial authority' },
      { number: 160, title: 'Independence of the Judiciary' },
      { number: 161, title: 'Judicial offices and officers' },
      { number: 162, title: 'System of courts' },
      { number: 163, title: 'Supreme Court' },
      { number: 164, title: 'Court of Appeal' },
      { number: 165, title: 'High Court' },
      { number: 166, title: 'Appointment of Chief Justice, Deputy Chief Justice and other judges' },
      { number: 167, title: 'Tenure of office of the Chief Justice and other judges' },
      { number: 168, title: 'Removal from office' },
      { number: 169, title: 'Subordinate courts' },
      { number: 170, title: 'Kadhis’ courts' },
      { number: 171, title: 'Establishment of the Judicial Service Commission' },
      { number: 172, title: 'Functions of the Judicial Service Commission' },
      { number: 173, title: 'Judiciary Fund' },
    ],
    dataPath: '/data/constitution/chapter-10.json',
    highlight:
      'Article 160 insulates the Judiciary from political control — judges answer to the Constitution, not to the executive.',
  },
  {
    number: 11,
    title: 'Devolved Government',
    summary:
      'The creation of 47 counties, their powers, and how they share revenue.',
    articleRange: [174, 200],
    articleTitles: [
      { number: 174, title: 'Objects of devolution' },
      { number: 175, title: 'Principles of devolved government' },
      { number: 176, title: 'County governments' },
      { number: 177, title: 'Membership of county assembly' },
      { number: 178, title: 'Speaker of a county assembly' },
      { number: 179, title: 'County executive committees' },
      { number: 180, title: 'Election of county governor and deputy county governor' },
      { number: 181, title: 'Removal of a county governor' },
      { number: 182, title: 'Vacancy in the office of county governor' },
      { number: 183, title: 'Functions of county executive committees' },
      { number: 184, title: 'Urban areas and cities' },
      { number: 185, title: 'Legislative authority of county assemblies' },
      { number: 186, title: 'Respective functions and powers of national and county governments' },
      { number: 187, title: 'Transfer of functions and powers between levels of government' },
      { number: 188, title: 'Boundaries of counties' },
      { number: 189, title: 'Cooperation between national and county governments' },
      { number: 190, title: 'Support for county governments' },
      { number: 191, title: 'Conflict of laws' },
      { number: 192, title: 'Suspension of a county government' },
      { number: 193, title: 'Qualifications for election as member of county assembly' },
      { number: 194, title: 'Vacation of office of member of county assembly' },
      { number: 195, title: 'County assembly power to summon witnesses' },
      { number: 196, title: 'Public participation and county assembly powers, privileges and immunities' },
      { number: 197, title: 'County assembly gender balance and diversity' },
      { number: 198, title: 'County government during transition' },
      { number: 199, title: 'Publication of county legislation' },
      { number: 200, title: 'Legislation on Chapter' },
    ],
    dataPath: '/data/constitution/chapter-11.json',
    highlight:
      '47 county governments exist to bring service delivery closer to every Kenyan.',
  },
  {
    number: 12,
    title: 'Public Finance',
    summary:
      'The rules that govern how public money is raised, spent, and audited.',
    articleRange: [201, 231],
    articleTitles: [
      { number: 201, title: 'Principles of public finance' },
      { number: 202, title: 'Equitable sharing of national revenue' },
      { number: 203, title: 'Equitable share and other financial laws' },
      { number: 204, title: 'Equalisation Fund' },
      { number: 205, title: 'Consultation on financial legislation affecting counties' },
      { number: 206, title: 'Consolidated Fund and other public funds' },
      { number: 207, title: 'Revenue Funds for county governments' },
      { number: 208, title: 'Contingencies Fund' },
      { number: 209, title: 'Power to impose taxes and charges' },
      { number: 210, title: 'Imposition of tax' },
      { number: 211, title: 'Borrowing by national government' },
      { number: 212, title: 'Borrowing by counties' },
      { number: 213, title: 'Loan guarantees by national government' },
      { number: 214, title: 'Public debt' },
      { number: 215, title: 'Commission on Revenue Allocation' },
      { number: 216, title: 'Functions of the Commission on Revenue Allocation' },
      { number: 217, title: 'Division of revenue' },
      { number: 218, title: 'Annual Division and Allocation of Revenue Bills' },
      { number: 219, title: 'Transfer of equitable share' },
      { number: 220, title: 'Form, content and timing of budgets' },
      { number: 221, title: 'Budget estimates and annual Appropriation Bill' },
      { number: 222, title: 'Expenditure before annual budget is passed' },
      { number: 223, title: 'Supplementary appropriation' },
      { number: 224, title: 'County appropriation Bills' },
      { number: 225, title: 'Financial control' },
      { number: 226, title: 'Accounts and audit of public entities' },
      { number: 227, title: 'Procurement of public goods and services' },
      { number: 228, title: 'Controller of Budget' },
      { number: 229, title: 'Auditor-General' },
      { number: 230, title: 'Salaries and Remuneration Commission' },
      { number: 231, title: 'Central Bank of Kenya' },
    ],
    dataPath: '/data/constitution/chapter-12.json',
    highlight:
      'Article 229 establishes the Auditor-General — the watchdog who confirms whether public money was spent lawfully.',
  },
  {
    number: 13,
    title: 'The Public Service',
    summary:
      'Values, principles, and the commissions that hire, oversee, and discipline public servants.',
    articleRange: [232, 237],
    articleTitles: [
      { number: 232, title: 'Values and principles of public service' },
      { number: 233, title: 'The Public Service Commission' },
      { number: 234, title: 'Functions and powers of the Public Service Commission' },
      { number: 235, title: 'Staffing of county governments' },
      { number: 236, title: 'Protection of public officers' },
      { number: 237, title: 'Teachers Service Commission' },
    ],
    dataPath: '/data/constitution/chapter-13.json',
    highlight:
      'Article 232 holds every public servant to efficient, responsive, and accountable service — auditable by design.',
  },
  {
    number: 14,
    title: 'National Security',
    summary:
      'The defence forces, intelligence service, police service — and the civilian oversight of each.',
    articleRange: [238, 247],
    articleTitles: [
      { number: 238, title: 'Principles of national security' },
      { number: 239, title: 'National security organs' },
      { number: 240, title: 'Establishment of the National Security Council' },
      { number: 241, title: 'Establishment of Defence Forces and Defence Council' },
      { number: 242, title: 'Establishment of National Intelligence Service' },
      { number: 243, title: 'Establishment of the National Police Service' },
      { number: 244, title: 'Objects and functions of the National Police Service' },
      { number: 245, title: 'Command of the National Police Service' },
      { number: 246, title: 'National Police Service Commission' },
      { number: 247, title: 'Other police services' },
    ],
    dataPath: '/data/constitution/chapter-14.json',
    highlight:
      'Article 239 places every security organ under civilian oversight — no service sits above the Constitution.',
  },
  {
    number: 15,
    title: 'Commissions and Independent Offices',
    summary:
      'The constitutional commissions and independent offices designed to survive every change of government.',
    articleRange: [248, 254],
    articleTitles: [
      { number: 248, title: 'Application of Chapter' },
      { number: 249, title: 'Objects, authority and funding of commissions and independent offices' },
      { number: 250, title: 'Composition, appointment and terms of office' },
      { number: 251, title: 'Removal from office' },
      { number: 252, title: 'General functions and powers' },
      { number: 253, title: 'Incorporation of commissions and independent offices' },
      { number: 254, title: 'Reporting by commissions and independent offices' },
    ],
    dataPath: '/data/constitution/chapter-15.json',
    highlight:
      'Article 249 gives each commission the independence to protect sovereignty, integrity, and the rule of law.',
  },
  {
    number: 16,
    title: 'Amendment of This Constitution',
    summary:
      'How this Constitution can be amended — by parliamentary supermajority or by referendum of the people.',
    articleRange: [255, 257],
    articleTitles: [
      { number: 255, title: 'Amendment of this Constitution' },
      { number: 256, title: 'Amendment by parliamentary initiative' },
      { number: 257, title: 'Amendment by popular initiative' },
    ],
    dataPath: '/data/constitution/chapter-16.json',
    highlight:
      'Article 255 lists the matters that can only be changed with the people\'s direct vote, not Parliament alone.',
  },
  {
    number: 17,
    title: 'General Provisions',
    summary:
      'Definitions, authoritative versions, and the interpretation rules that bind the whole document.',
    articleRange: [258, 260],
    articleTitles: [
      { number: 258, title: 'Enforcement of this Constitution' },
      { number: 259, title: 'Construing this Constitution' },
      { number: 260, title: 'Interpretation' },
    ],
    dataPath: '/data/constitution/chapter-17.json',
  },
  {
    number: 18,
    title: 'Transitional and Consequential Provisions',
    summary:
      'How the 2010 Constitution replaced the old order, and the timeline for enacting the laws it requires.',
    articleRange: [261, 264],
    articleTitles: [
      { number: 261, title: 'Consequential legislation' },
      { number: 262, title: 'Transitional and consequential provisions' },
      { number: 263, title: 'Effective Date' },
      { number: 264, title: 'Repeal of previous constitution' },
    ],
    dataPath: '/data/constitution/chapter-18.json',
    highlight:
      'Article 261 is the schedule Parliament had to keep — every law required by the new Constitution, listed and timed.',
  },
];

/** Total number of articles covered across the chapters we publish. */
export const TOTAL_ARTICLES = CONSTITUTION_META.reduce(
  (sum, c) => sum + c.articleTitles.length,
  0
);

/** Quick lookup: article number → chapter metadata. */
const ARTICLE_TO_CHAPTER = new Map<number, ChapterMeta>();
for (const ch of CONSTITUTION_META) {
  for (const a of ch.articleTitles) {
    ARTICLE_TO_CHAPTER.set(a.number, ch);
  }
}

export function findChapterForArticle(articleNumber: number): ChapterMeta | undefined {
  return ARTICLE_TO_CHAPTER.get(articleNumber);
}

/** In-memory cache of loaded chapters so we never re-fetch the same one. */
const CHAPTER_CACHE = new Map<number, ConstitutionChapter>();
let ALL_LOADED_PROMISE: Promise<ConstitutionChapter[]> | null = null;

export async function loadChapter(
  chapterNumber: number
): Promise<ConstitutionChapter | null> {
  const cached = CHAPTER_CACHE.get(chapterNumber);
  if (cached) return cached;
  const meta = CONSTITUTION_META.find((c) => c.number === chapterNumber);
  if (!meta) return null;
  try {
    const res = await fetch(meta.dataPath, { cache: 'force-cache' });
    if (!res.ok) return null;
    const data = (await res.json()) as ConstitutionChapter;
    CHAPTER_CACHE.set(chapterNumber, data);
    return data;
  } catch {
    return null;
  }
}

/**
 * Load every chapter — used when the user engages full-text search and
 * asks for keyword matches across the whole Constitution. The promise
 * is memoised so concurrent searches share one fetch batch.
 */
export function loadAllChapters(): Promise<ConstitutionChapter[]> {
  if (!ALL_LOADED_PROMISE) {
    ALL_LOADED_PROMISE = Promise.all(
      CONSTITUTION_META.map((m) => loadChapter(m.number))
    ).then((results) => results.filter((c): c is ConstitutionChapter => c !== null));
  }
  return ALL_LOADED_PROMISE;
}
